const config = window.STEWARD_PORTAL_CONFIG || {};
const SUPABASE_URL = config.supabaseUrl || "YOUR_SUPABASE_URL";
const SUPABASE_ANON_KEY = config.supabaseAnonKey || "YOUR_SUPABASE_ANON_KEY";
const DOCUMENT_BUCKET = config.documentBucket || "steward-documents";
const INTERNAL_BUCKET = config.internalBucket || "internal-files";
const isConfigured = SUPABASE_URL.startsWith("https://") && SUPABASE_ANON_KEY.length > 30;
const isLocalhost = ["localhost", "127.0.0.1", ""].includes(window.location.hostname);
const previewMode = !isConfigured && isLocalhost && new URLSearchParams(window.location.search).get("preview") === "1";
const supabaseClient = isConfigured ? window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY) : null;

const sampleCases = [
  { id: "preview-1", member_name: "Sample Member", member_contact: "member@example.ca", contract: "Contract 1", issue_type: "Grievance", status: "Intake", next_deadline: nextDate(3), next_action: "Confirm facts and collect supporting documents", summary: "Example intake for a scheduling dispute.", created_at: new Date().toISOString() },
  { id: "preview-2", member_name: "Training Case", member_contact: "555-0100", contract: "Contract 2", issue_type: "Payroll", status: "Waiting on company", next_deadline: nextDate(6), next_action: "Follow up with company representative", summary: "Example payroll claim tracking item.", created_at: new Date().toISOString() }
];
const sampleResources = [
  { id: "r1", title: "Collective Agreements", category: "Agreements", contract: "Shared", description: "Protected links to Contract 1 and Contract 2 reference copies." },
  { id: "r2", title: "Grievance Template", category: "Templates", contract: "Shared", description: "Standard form language and filing checklist." }
];
const publicAnnouncements = [
  { title: "Welcome to the Local 4005 Moncton union board", date: "2026-06-10", contract: "Shared", category: "Notice", summary: "Public notices, member resources, and Contract 1 / Contract 2 updates will appear here." },
  { title: "Current VIA Rail agreements", date: "2026-06-11", contract: "Shared", category: "Agreements", summary: "Council 4000 lists VIA Rail Agreement No. 1 and No. 2 as 2025-2027." }
];
const publicResources = [
  { title: "VIA Rail Agreement No. 1", category: "Agreements", contract: "Contract 1", description: "Council 4000 lists Agreement No. 1 - National as 2025-2027.", url: "https://www.unifor4000.com/collective-agreements" },
  { title: "VIA Rail Agreement No. 2", category: "Agreements", contract: "Contract 2", description: "Council 4000 lists Agreement No. 2 - National as 2025-2027.", url: "https://www.unifor4000.com/collective-agreements" },
  { title: "VIA supplemental and safety agreements", category: "Agreements", contract: "Shared", description: "Agreement supplementals and Safety and Health Agreement are linked from Council 4000.", url: "https://www.unifor4000.com/collective-agreements" },
  { title: "Council 4000 bylaws", category: "Bylaws", contract: "Shared", description: "Council 4000 bylaws and constitution resources.", url: "https://www.unifor4000.com/bylaws-constitution" },
  { title: "Grievance forms", category: "Grievance", contract: "Shared", description: "Council 4000 grievance forms, including Local 4005.", url: "https://www.unifor4000.com/grievance-forms" },
  { title: "Union Savings discounts", category: "Discounts", contract: "Shared", description: "Member discount platform linked from Council 4000 resources.", url: "https://unionsavings.ca/en" },
  { title: "Contact a steward", category: "Support", contract: "Shared", description: "Use this area for approved contact instructions." }
];
const publicKnowledge = [
  { title: "VIA Rail Agreement No. 1", category: "Agreements", text: "Council 4000 lists VIA Rail Agreement No. 1 - National as 2025-2027." },
  { title: "VIA Rail Agreement No. 2", category: "Agreements", text: "Council 4000 lists VIA Rail Agreement No. 2 - National as 2025-2027." },
  { title: "Bylaws", category: "Bylaws", text: "Council 4000 bylaws and the Unifor Constitution are public resources linked from the Council 4000 bylaws page." },
  { title: "Discounts", category: "Discounts", text: "Union Savings is linked from Council 4000 resources as the member discount platform." }
];
let currentUser = null, currentProfile = null, selectedCaseId = null;
let cases = [], resources = [], notes = [], documents = [], pendingProfiles = [], internalFiles = [];
let publicQuestions = [{ id: "q1", name: "Member", question: "Where are the current agreements?", answer: "Use the Agreement No. 1 and No. 2 links in Member resources.", created_at: new Date().toISOString() }];
const app = document.querySelector("#app");

if (previewMode) {
  currentUser = { id: "preview-user", email: "preview@local4005.test" };
  currentProfile = { id: "preview-user", full_name: "Preview Admin", role: "admin" };
  cases = [...sampleCases]; resources = [...sampleResources];
  pendingProfiles = [{ id: "pending-1", full_name: "New Steward", email: "new.steward@example.ca", role: "steward", request_note: "Moncton steward access request", created_at: new Date().toISOString() }];
  internalFiles = [{ id: "file-1", file_name: "Locked-Grievance-Tracker.xlsx", kind: "grievance_tracker", storage_path: "grievance-tracker/Locked-Grievance-Tracker.xlsx", uploaded_at: new Date().toISOString() }];
  renderPortal();
} else { if (isConfigured) startAuthenticatedApp(); wirePublicBoard(); }

async function startAuthenticatedApp() {
  const { data } = await supabaseClient.auth.getUser(); currentUser = data.user; if (!currentUser) return;
  const { data: profile, error } = await supabaseClient.from("profiles").select("*").eq("id", currentUser.id).single();
  if (error || !profile?.active) { await supabaseClient.auth.signOut(); const m = document.querySelector("#auth-message"); if (m) m.textContent = "This account is not approved yet."; return; }
  currentProfile = profile; await loadData(); renderPortal();
}
function wirePublicBoard() { renderPublicBoard(); document.querySelector("#staff-login")?.addEventListener("click", renderAuth); document.querySelector("#assistant-ask")?.addEventListener("click", answerPublicQuestion); document.querySelector("#question-form")?.addEventListener("submit", submitPublicQuestion); ["public-search", "public-contract"].forEach((id) => document.querySelector(`#${id}`)?.addEventListener("input", renderPublicBoard)); }
function renderPublicBoard() {
  const term = value("public-search").toLowerCase(), contract = document.querySelector("#public-contract")?.value || "all";
  const match = (x) => (!term || [x.title, x.category, x.contract, x.summary, x.description].join(" ").toLowerCase().includes(term)) && (contract === "all" || x.contract === contract || x.contract === "Shared");
  const announcements = publicAnnouncements.filter(match); document.querySelector("#announcement-total").textContent = `${announcements.length} shown`;
  document.querySelector("#announcement-list").innerHTML = announcements.map((x) => `<article class="announcement-card"><div class="meta-row"><span class="pill">${e(x.contract)}</span><span class="pill">${e(x.category)}</span><span class="pill">${e(x.date)}</span></div><h3>${e(x.title)}</h3><p>${e(x.summary)}</p></article>`).join("") || `<div class="empty">No public notices match.</div>`;
  const rows = publicResources.filter(match); document.querySelector("#public-resource-list").innerHTML = rows.map((x) => `<article class="resource-item"><h3>${e(x.title)}</h3><p>${e(x.description)}</p><div class="meta-row"><span class="pill">${e(x.category)}</span><span class="pill">${e(x.contract)}</span>${x.url ? `<a class="pill" href="${e(x.url)}" target="_blank" rel="noopener">Open</a>` : ""}</div></article>`).join("") || `<div class="empty">No resources match.</div>`;
  renderQABoard();
}
async function answerPublicQuestion() {
  const question = value("assistant-question"); const box = document.querySelector("#assistant-answer"); if (!question) { box.textContent = "Type a question first."; return; }
  box.textContent = "Checking agreement assistant...";
  try { const r = await fetch("/api/ask", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question }) }); if (r.ok) { const d = await r.json(); box.innerHTML = `<p>${e(d.answer)}</p>${d.sources?.length ? `<div class="meta-row">${d.sources.map((s) => `<a class="pill" href="${e(s.url)}" target="_blank" rel="noopener">${e(s.title)}</a>`).join("")}</div>` : ""}`; return; } } catch {}
  const q = question.toLowerCase(); const m = publicKnowledge.filter((x) => [x.title, x.category, x.text].join(" ").toLowerCase().includes(q) || q.split(/\s+/).some((w) => w.length > 2 && x.text.toLowerCase().includes(w)));
  box.innerHTML = m.length ? m.map((x) => `<p><strong>${e(x.title)}:</strong> ${e(x.text)}</p>`).join("") : `<p>No matching public note yet. Submit it to the Q&A board.</p>`;
}
async function submitPublicQuestion(ev) { ev.preventDefault(); const name = value("question-name") || "Anonymous", question = value("question-body"), msg = document.querySelector("#question-message"); if (!question) return; if (isConfigured) { const { error } = await supabaseClient.from("public_questions").insert({ name, question }); msg.textContent = error ? error.message : "Question submitted for review."; } else { publicQuestions.unshift({ id: crypto.randomUUID(), name, question, answer: "Pending review.", created_at: new Date().toISOString() }); msg.textContent = "Question added locally for preview."; renderQABoard(); } document.querySelector("#question-form").reset(); }
function renderQABoard() { const list = document.querySelector("#qa-list"); if (list) list.innerHTML = publicQuestions.map((x) => `<article class="qa-card"><h3>${e(x.question)}</h3><p>${e(x.answer || "Pending review.")}</p><div class="meta-row"><span class="pill">${e(x.name || "Anonymous")}</span></div></article>`).join(""); }
function renderAuth() { app.innerHTML = document.querySelector("#auth-template").innerHTML; document.querySelector("#back-public").addEventListener("click", () => location.reload()); document.querySelector("#request-access").addEventListener("click", renderRegister); document.querySelector("#login-form").addEventListener("submit", async (ev) => { ev.preventDefault(); const m = document.querySelector("#auth-message"); if (!isConfigured) { m.textContent = "Supabase is not configured yet."; return; } const { error } = await supabaseClient.auth.signInWithPassword({ email: value("email"), password: value("password") }); m.textContent = error ? error.message : "Signed in."; if (!error) await startAuthenticatedApp(); }); }
function renderRegister() { app.innerHTML = document.querySelector("#register-template").innerHTML; document.querySelector("#back-login").addEventListener("click", renderAuth); document.querySelector("#register-form").addEventListener("submit", async (ev) => { ev.preventDefault(); const m = document.querySelector("#register-message"); if (!isConfigured) { m.textContent = "Supabase is not configured yet."; return; } const { error } = await supabaseClient.auth.signUp({ email: value("register-email"), password: value("register-password"), options: { data: { full_name: value("register-name"), requested_role: value("register-role"), request_note: value("register-note") } } }); m.textContent = error ? error.message : "Request submitted. An admin must approve the account."; if (!error) document.querySelector("#register-form").reset(); }); }
async function loadData() { const [c, r, p, f] = await Promise.all([supabaseClient.from("cases").select("*").order("updated_at", { ascending: false }), supabaseClient.from("resources").select("*").order("category"), currentProfile.role === "admin" ? supabaseClient.from("profiles").select("*").eq("active", false).eq("access_status", "pending").order("created_at") : Promise.resolve({ data: [] }), supabaseClient.from("internal_files").select("*").order("uploaded_at", { ascending: false })]); cases = c.data || []; resources = r.data || []; pendingProfiles = p.data || []; internalFiles = f.data || []; selectedCaseId = cases[0]?.id || null; if (selectedCaseId) await loadCaseChildren(selectedCaseId); }
async function loadCaseChildren(id) { if (previewMode) { notes = [{ body: "Preview note.", created_at: new Date().toISOString() }]; documents = []; return; } const [n, d] = await Promise.all([supabaseClient.from("case_notes").select("*").eq("case_id", id).order("created_at", { ascending: false }), supabaseClient.from("case_documents").select("*").eq("case_id", id).order("created_at", { ascending: false })]); notes = n.data || []; documents = d.data || []; }
function renderPortal() { app.innerHTML = document.querySelector("#portal-template").innerHTML; document.querySelector("#user-label").textContent = `${currentProfile.full_name || currentUser.email} (${currentProfile.role})`; wirePortalEvents(); selectedCaseId = selectedCaseId || cases[0]?.id || null; renderAll(); }
function wirePortalEvents() { document.querySelector("#sign-out").addEventListener("click", async () => { if (supabaseClient) await supabaseClient.auth.signOut(); location.href = location.pathname; }); ["search", "contract-filter", "status-filter"].forEach((id) => document.querySelector(`#${id}`).addEventListener("input", renderAll)); document.querySelector("#new-case").addEventListener("click", clearCaseForm); document.querySelector("#save-case").addEventListener("click", saveCase); document.querySelector("#document-upload").addEventListener("change", uploadDocument); document.querySelector("#internal-file-upload").addEventListener("change", uploadInternalFile); }
function renderAll() { renderStats(); renderCases(); renderCaseForm(); renderResources(); renderApprovals(); renderInternalFiles(); }
function renderStats() { const open = cases.filter((x) => !["Resolved", "Withdrawn"].includes(x.status)); document.querySelector("#open-count").textContent = open.length; document.querySelector("#deadline-count").textContent = open.filter((x) => x.next_deadline && daysUntil(x.next_deadline) <= 7 && daysUntil(x.next_deadline) >= 0).length; document.querySelector("#waiting-count").textContent = cases.filter((x) => x.status === "Waiting on company").length; document.querySelector("#resolved-count").textContent = cases.filter((x) => x.status === "Resolved").length; }
function filteredCases() { const term = value("search").toLowerCase(), contract = document.querySelector("#contract-filter")?.value || "all", status = document.querySelector("#status-filter")?.value || "all"; return cases.filter((x) => (!term || [x.member_name, x.member_contact, x.issue_type, x.status, x.summary, x.next_action].join(" ").toLowerCase().includes(term)) && (contract === "all" || x.contract === contract) && (status === "all" || x.status === status)); }
function renderCases() { const rows = filteredCases(); document.querySelector("#case-total").textContent = `${rows.length} shown`; document.querySelector("#case-list").innerHTML = rows.map((x) => `<button class="case-card ${x.id === selectedCaseId ? "active" : ""}" type="button" data-case-id="${x.id}"><h3>${e(x.member_name)}</h3><p>${e(x.issue_type)} · ${e(x.next_action || "No next action set")}</p><div class="meta-row"><span class="pill">${e(x.contract)}</span><span class="pill">${e(x.status)}</span>${x.next_deadline ? `<span class="pill">${e(x.next_deadline)}</span>` : ""}</div></button>`).join("") || `<div class="empty">No cases match.</div>`; document.querySelectorAll("[data-case-id]").forEach((b) => b.addEventListener("click", async () => { selectedCaseId = b.dataset.caseId; await loadCaseChildren(selectedCaseId); renderAll(); })); }
function renderCaseForm() { const x = cases.find((row) => row.id === selectedCaseId); if (!x) return clearCaseForm(); ["member-name", "member-contact", "case-contract", "issue-type", "case-status", "next-deadline", "next-action", "summary"].forEach((id) => setValue(id, { "member-name": x.member_name, "member-contact": x.member_contact, "case-contract": x.contract, "issue-type": x.issue_type, "case-status": x.status, "next-deadline": x.next_deadline, "next-action": x.next_action, summary: x.summary }[id])); setValue("case-id", x.id); setValue("new-note", ""); renderDocuments(); renderActivity(); }
function renderResources() { document.querySelector("#resource-list").innerHTML = resources.map((x) => `<article class="resource-item"><h3>${e(x.title)}</h3><p>${e(x.description || "")}</p><div class="meta-row"><span class="pill">${e(x.category)}</span><span class="pill">${e(x.contract)}</span></div></article>`).join("") || `<div class="empty">No steward resources yet.</div>`; }
function renderApprovals() { const panel = document.querySelector("#approval-panel"); if (currentProfile.role !== "admin") { panel.hidden = true; return; } panel.hidden = false; document.querySelector("#approval-total").textContent = `${pendingProfiles.length} pending`; document.querySelector("#approval-list").innerHTML = pendingProfiles.map((x) => `<article class="approval-card"><div><h3>${e(x.full_name)}</h3><p>${e(x.email || "")}</p><p>${e(x.request_note || "No reason provided.")}</p><div class="meta-row"><span class="pill">${e(x.role)}</span></div></div><div class="button-row"><button data-approve-id="${x.id}">Approve</button><button class="secondary" data-reject-id="${x.id}">Reject</button></div></article>`).join("") || `<div class="empty">No access requests.</div>`; document.querySelectorAll("[data-approve-id]").forEach((b) => b.addEventListener("click", () => updateAccessRequest(b.dataset.approveId, true))); document.querySelectorAll("[data-reject-id]").forEach((b) => b.addEventListener("click", () => updateAccessRequest(b.dataset.rejectId, false))); }
async function updateAccessRequest(id, approved) { if (previewMode) { pendingProfiles = pendingProfiles.filter((x) => x.id !== id); return renderApprovals(); } const payload = approved ? { active: true, access_status: "approved", approved_by: currentUser.id, approved_at: new Date().toISOString() } : { active: false, access_status: "rejected", approved_by: currentUser.id, approved_at: new Date().toISOString() }; const { error } = await supabaseClient.from("profiles").update(payload).eq("id", id); if (error) return alert(error.message); await loadData(); renderApprovals(); }
function renderInternalFiles() { const canTracker = currentProfile.role === "steward"; const select = document.querySelector("#internal-file-kind"); if (select) select.querySelector('[value="grievance_tracker"]').disabled = !canTracker; const rows = internalFiles.filter((x) => x.kind !== "grievance_tracker" || canTracker); document.querySelector("#internal-file-list").innerHTML = rows.map((x) => `<article class="file-card"><div><h3>${e(x.file_name)}</h3><p>${x.kind === "grievance_tracker" ? "Locked grievance tracker Excel" : "General internal file"}</p></div><button data-internal-path="${e(x.storage_path)}">Open</button></article>`).join("") || `<div class="empty">No internal files uploaded yet.</div>`; document.querySelectorAll("[data-internal-path]").forEach((b) => b.addEventListener("click", () => openInternalFile(b.dataset.internalPath))); }
async function uploadInternalFile(ev) { const file = ev.target.files[0]; if (!file) return; const kind = value("internal-file-kind"); if (kind === "grievance_tracker" && currentProfile.role !== "steward") { alert("Only stewards can upload the locked grievance tracker."); ev.target.value = ""; return; } if (kind === "grievance_tracker" && !/\.(xlsx|xls|xlsm)$/i.test(file.name)) { alert("Use an Excel workbook for the grievance tracker."); ev.target.value = ""; return; } if (previewMode) { internalFiles.unshift({ id: crypto.randomUUID(), file_name: file.name, kind, storage_path: `${kind}/${file.name}` }); renderInternalFiles(); ev.target.value = ""; return; } const folder = kind === "grievance_tracker" ? "grievance-tracker" : "general", storage_path = `${folder}/${Date.now()}-${file.name}`; const up = await supabaseClient.storage.from(INTERNAL_BUCKET).upload(storage_path, file); if (up.error) return alert(up.error.message); const rec = await supabaseClient.from("internal_files").insert({ file_name: file.name, kind, storage_path, mime_type: file.type, file_size: file.size, uploaded_by: currentUser.id }); if (rec.error) return alert(rec.error.message); await loadData(); renderInternalFiles(); ev.target.value = ""; }
async function openInternalFile(path) { if (previewMode) return alert("File download is available after Supabase storage is configured."); const { data, error } = await supabaseClient.storage.from(INTERNAL_BUCKET).createSignedUrl(path, 300); if (error) return alert(error.message); open(data.signedUrl, "_blank", "noopener"); }
function renderDocuments() { document.querySelector("#document-list").innerHTML = documents.map((x) => `<li><strong>${e(x.file_name)}</strong><button class="secondary" data-doc-path="${e(x.storage_path)}">Open</button></li>`).join("") || `<li class="empty">No documents uploaded.</li>`; }
function renderActivity() { document.querySelector("#activity-list").innerHTML = notes.map((x) => `<li><strong>${new Date(x.created_at).toLocaleString()}</strong><p>${e(x.body)}</p></li>`).join("") || `<li class="empty">No activity yet.</li>`; }
function clearCaseForm() { selectedCaseId = null; ["case-id", "member-name", "member-contact", "next-deadline", "next-action", "summary", "new-note"].forEach((id) => setValue(id, "")); setValue("case-contract", "Contract 1"); setValue("issue-type", "Grievance"); setValue("case-status", "Intake"); documents = []; notes = []; renderDocuments(); renderActivity(); }
async function saveCase() { const payload = { member_name: value("member-name"), member_contact: value("member-contact"), contract: value("case-contract"), issue_type: value("issue-type"), status: value("case-status"), next_deadline: value("next-deadline") || null, next_action: value("next-action"), summary: value("summary"), updated_by: currentUser.id }; if (previewMode) { const id = value("case-id") || crypto.randomUUID(); const i = cases.findIndex((x) => x.id === id); const row = { ...payload, id }; if (i >= 0) cases[i] = row; else cases.unshift(row); selectedCaseId = id; renderAll(); return; } const id = value("case-id"); const res = id ? await supabaseClient.from("cases").update(payload).eq("id", id).select().single() : await supabaseClient.from("cases").insert({ ...payload, created_by: currentUser.id }).select().single(); if (res.error) return alert(res.error.message); selectedCaseId = res.data.id; await loadData(); renderAll(); }
async function uploadDocument() {}
function value(id) { return document.querySelector(`#${id}`)?.value?.trim() || ""; }
function setValue(id, v) { const el = document.querySelector(`#${id}`); if (el) el.value = v || ""; }
function nextDate(n) { const d = new Date(); d.setDate(d.getDate() + n); return d.toISOString().slice(0, 10); }
function daysUntil(s) { const d = new Date(`${s}T00:00:00`), t = new Date(); t.setHours(0,0,0,0); return Math.ceil((d - t) / 86400000); }
function e(text) { return String(text || "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[c])); }
